name: Unit Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Tests
        working-directory: "./server"
        run: |
          npm install
          npm test
